language: java

jdk:
  - oraclejdk8

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn deploy

before_install:
- openssl aes-256-cbc -K $encrypted_7388fc7fce2d_key -iv $encrypted_7388fc7fce2d_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml

script: 
- export PROFILES=normalProfile
- mvn -DupdateSiteFolder=$UPDATE_SITE -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install jacoco:report coveralls:report -P $PROFILES

notifications:
  email:
  - arena-uqbar@googlegroups.com
cache:
  directories:
  - $HOME/.m2
